---
- name: check or install required packages
  yum: name={{ item }} state=latest
  with_items:
    - libvirt
    - qemu-kvm
    - net-tools

- name: make sure libvirtd is started
  service: name=libvirtd state=started

- name: remove tripleo vms working dir
  file:
    path: "{{ oooq_vms_path }}"
    state: absent
  become: true

# @TODO matbu: make a teardown set of tasks and tags
- name: destroy vms
  ignore_errors: true
  with_items: "{{ vms }}"
  shell: >
    virsh destroy {{ item }};
    virsh undefine {{ item }};

- name: destroy network if exist
  ignore_errors: true
  with_items: "{{ networks_name }}"
  shell: >
    if virsh net-list | grep {{ item }}; then
        virsh net-destroy {{ item }};
        virsh net-undefine {{ item }}
    fi

- name: destroy pool
  register: destroypool
  ignore_errors: true
  shell: >
    virsh pool-destroy {{ pool_name }}

- name: force remove pool
  when: destroypool.rc == 1
  shell: >
    rm -f /var/run/libvirt/storage/{{ pool_name }}.xml;
    systemctl restart libvirtd

- name: download tar file
  register: download
  get_url:
    url: "{{ proto }}://{{ http_server }}/{{ http_path }}/{{ oooq_tar_name }}"
    dest: "{{ oooq_tar_path }}/{{ oooq_tar_name }}"

- name: test if oooq tmp tar dir is present
  register: test_dir
  ignore_errors: true
  shell: >
    test -d "{{ oooq_tar_path }}/var/oooqvms"

- name: create tripleo vms working dir
  when: test_dir.rc != 0
  file:
    path: "{{ oooq_tar_path }}"
    state: directory
  become: true

- name: untar tripleo vms
  when: download.changed|bool or test_dir.rc != 0
  shell: >
    pushd "{{ oooq_tar_path }}";
    tar -xvzf "{{ oooq_tar_name }}"

# @TODO: matbu test out this rather than fetch and untar
#    src: "{{ proto }}://{{ http_server }}/{{ http_path }}/{{ oooq_tar_name }}"

- name: move oooq file
  shell: >
    mv /tmp/var/oooqvms {{ oooq_vms_path }}

- name: create oooq_pool
  shell: >
    virsh pool-create {{ oooq_vms_path }}/{{ pool_name }}.xml

- name: create networks
  shell: >
    virsh net-create {{ oooq_vms_path }}/{{ item }}.xml
  with_items: "{{ networks_name }}"

- name: start vms
  shell: >
    virsh create {{ oooq_vms_path }}/{{ item }}.xml
  with_items: "{{ vms }}"

- name: check for ssh config args in ansible.cfg
  register: ssh_args
  ignore_errors: true
  shell: >
    grep ssh.config.ansible ansible.cfg
