---
- name: Restore oooq deployment
  hosts: virthost
  gather_facts: no
  tags:
    - tripleo-restore
  roles:
    - { role: tripleo-backup,
        restore: true,
        jenkins: true,
        oooq_tar_path: '/home' }

- name: Sanity checks the undercloud services
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-restore-uc-sanity
  roles:
    - { role: tripleo-backup,
        sanity: true,
        services: ["openstack-keystone", "openstack-glance-api"] }

- name: Sanity checks the overcloud services
  hosts: overcloud
  gather_facts: no
  tags:
    - tripleo-restore-uc-sanity
  roles:
    - { role: tripleo-backup,
        sanity: true,
        services: ["openstack-keystone", "openstack-glance-api", "neutron-server"] }
