---
- name: Restore oooq deployment
  hosts: virthost
  tags:
    - tripleo-restore
  roles:
    - { role: ansible-role-tripleo-backup,
        restore: true }

- name: Sanity checks the undercloud services
  hosts: undercloud
  tags:
    - tripleo-restore-uc-sanity
  roles:
    - { role: ansible-role-tripleo-backup,
        restore: true,
        services: ["keystone", "glance-api"] }

- name: Sanity checks the overcloud services
  hosts: overcloud
  tags:
    - tripleo-restore-uc-sanity
  roles:
    - { role: ansible-role-tripleo-backup,
        restore: true,
        services: ["keystone", "glance-api", "neutron-server"] }
