---
- name: Restore oooq deployment
  hosts: virthost
  gather_facts: no
  tags:
    - tripleo-restore
  roles:
    - { role: tripleo-backup,
        restore: true,
        restore_config: true,
        oooq_tar_path: '/home' }
