---
- name: Sanity checks the undercloud services
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-restore-uc-sanity
  roles:
    - { role: tripleo-backup,
        sanity: true,
        services: ["openstack-glance-api"] }

- name: Sanity checks the overcloud services
  hosts: overcloud
  gather_facts: no
  tags:
    - tripleo-restore-oc-sanity
  roles:
    - { role: tripleo-backup,
        sanity: true,
        services: ["openstack-glance-api", "neutron-server"] }
